= CV - Akihiro Kiuchi
:toc: macro
:doctype: book

https://github.com/Aki-7[image:https://img.shields.io/badge/-Aki--7-eee?logo=github&style=for-the-badge&logoColor=333[GitHub]]
https://twitter.com/akihiro_kiuchi[image:https://img.shields.io/badge/-@akihiro__kiuchi-eee?logo=X&logoColor=000&style=for-the-badge[Twitter Follow]]
mailto:akihirorz@gmail.com[image:https://img.shields.io/badge/-Email-eee?logo=gmail&style=for-the-badge[Gmail]]
https://www.linkedin.com/in/akihiro-kiuchi-b6872b220/[image:https://img.shields.io/badge/-LinkedIn-eee?logo=linkedin&style=for-the-badge&logoColor=0077b5[Linkedin]]

== TL;DR

I'm a CTO and co-founder of ENIAQ Inc. I'm leading the technical and product development of the company. I'm hiring for the team in Tokyo, Japan.

[cols="1,1", options="header"]
|===
|Current Status
|Location

|I'm hiring 🤝
|Tokyo, Japan
|===

toc::[]

= Professional Experience

== Co-founder and CTO @ https://eniaq.jp[ENIAQ Inc.]

Roll:: May 2024 - now : *Co-founder and CTO*

* Leading technical and product development.

= Education

== Doctor of Information and Communication Engineering
_Apr 2023 - May 2024 (On leave since May 2024)_ +
The User Interface Research Group at the University of Tokyo, advised by Prof. Takeo Igarashi.

TL;DR::
*_New research area, international internship, three publications._* +
Moved to HCI/AR research, presented a demo at SIGGRAPH Asia 2023, and completed a 6-month research internship at Carnegie Mellon University, resulting in two conference papers (CHI 2025, ISMAR 2024).

=== Research Internship at the https://augmented-perception.org/[Augmented Perception Lab], Carnegie Mellon University*

_Oct 2023 - Apr 2024_

* Researched AR remote communication and mobile AR interaction, resulting in publications at CHI 2025 and ISMAR 2024.

=== Publications

* Akihiro Kiuchi, Jonathan Wieland, Takeo Igarashi, and David Lindlbauer. 2025. MiniMates: Miniature Avatars for AR Remote Meetings within Limited Physical Spaces. In Proceedings of the 2025 CHI Conference on Human Factors in Computing Systems (CHI '25). ACM, Article 708, 1–20. https://doi.org/10.1145/3706598.3714328
* Jonathan Wieland, Hyunsung Cho, Sebastian Hubenschmid, Akihiro Kiuchi, Harald Reiterer, and David Lindlbauer. 2024. Push2AR: Enhancing Mobile List Interactions Using Augmented Reality. In IEEE International Symposium on Mixed and Augmented Reality (ISMAR '24). https://doi.org/10.1109/ISMAR62088.2024.00082
* Akihiro Kiuchi, Anran Qi, Eve Mingxiao Li, Dávid Maruscsák, Christian Sandor, and Takeo Igarashi. 2023. PerfectFit: Custom-Fit Garment Design in Augmented Reality. In SIGGRAPH Asia 2023 XR (SA XR '23). ACM, 1–2. https://doi.org/10.1145/3610549.3614592

== Master of Information and Communication Engineering
_Apr 2021 - Mar 2023_

TL;DR::
*_OSS development and international programs._* +
Led the Zwin open-source project and participated in Google Summer of Code (see <<Projects & Internships>>).

GPA:: 3.80 / 4.00
footnote:[Calculated according to https://www.fulbright.jp/eng/index.html[Fulbright Japan] criteria, as my university does not provide an official GPA]

Thesis:: The design and implementation of a windowing system for multi-context immersive environments.

International conference::
Akihiro Kiuchi, Taishi Eguchi, Jun Rekimoto, Manabu Tsukada, and Hiroshi Esaki. 2022. ZIGEN: A Windowing System Enabling Multitasking Among 3D and 2D Applications in Immersive Environments. In ACM SIGGRAPH 2022 Posters (SIGGRAPH '22). Association for Computing Machinery, New York, NY, USA, Article 34, 1–2. https://doi.org/10.1145/3532719.3543200

== Bachelor of Information and Communication Engineering
_Apr 2017 - Mar 2021_

TL;DR::
*_Coursework and industry internships._* +
Focused on academics while gaining hands-on experience through software engineering internships (see <<Projects & Internships>>).

GPA:: 3.74 / 4.00
footnote:[Calculated according to https://www.fulbright.jp/eng/index.html[Fulbright Japan] criteria, as my university does not provide an official GPA]

Thesis::
Development of testbeds adapted to diverse environments for investigation of LANs in distant locations.

= Projects & Internships

== Zwin: XR Windowing System

https://www.zwin.dev[image:https://img.shields.io/badge/-🔗 website-eee?logo=link&style=for-the-badge[homepage]]
https://github.com/zwin-project[image:https://img.shields.io/badge/-zwin--project-eee?logo=github&style=for-the-badge&logoColor=333[GitHub]]
https://twitter.com/zwin_project[image:https://img.shields.io/badge/-@zwin__project-eee?logo=twitter&style=for-the-badge[Twitter Follow]]
https://www.youtube.com/@zwin_project[image:https://img.shields.io/badge/-Youtube-eee?logo=youtube&style=for-the-badge&logoColor=ff0000[youtube]]

Launched Zwin, an OSS project to realize a windowing system in XR.

Roll:: Jun 2021 - 2024 : *Technical Lead / Project Lead*

* Leading the technical part of the project, designing the overall code architecture, assigning development tasks, onboarding new members, forming a development culture and ensuring code quality through code reviews, and resolving technical issues.
* Leading the OSS project, presenting the project vision, facilitating regular meetings, setting milestones, building a team, networking, and presenting externally.
* Adopted as one of 8 groups for a government-funded 8-month development program
(https://www.ipa.go.jp/jinzai/advanced/2022/gaiyou_hn-1.html[2022, Mitou Advanced Program]).
* Adopted as one of 23 groups for a government-funded 9-month development program
(https://www.ipa.go.jp/jinzai/mitou/2021/gaiyou_sd-2.html[2021, Mitou Program]),
and awarded the title of honor "Super Creator" for outstanding progress during the program.

Skils:: C / C++ / Meson / CMake / OpenGL / OpenXR / Wayland / Windowing System / gRPC

Talks::
* https://youtu.be/g_MvbwKp8Uk[MITOU DEMO DAY Day2] (Japanese only, 19 min)
* https://www.youtube.com/live/ygleFityMWs?feature=share&t=1060[MITOU Night 2022] (Japanese only, 5 min)

== Jenkins Remoting Monitoring (Google Summer of Code)

https://www.jenkins.io/projects/gsoc/2021/projects/remoting-monitoring[image:https://img.shields.io/badge/-🔗 website-eee?logo=link&style=for-the-badge[homepage]]
https://github.com/jenkinsci/remoting-opentelemetry-plugin[image:https://img.shields.io/badge/-GitHub-eee?logo=github&style=for-the-badge&logoColor=333[GitHub]]

Roll:: Jun 2021 - Sep 2021 : *Google Summer of Code student contributor*

* Selected as one of 1292 participants out of 6991 applications worldwide for a 10-week OSS development program and completed the program (https://summerofcode.withgoogle.com/[Google Summer of Code]).
* Developed and released a Jenkins plugin as a maintainer to collect and send telemetry from the Jenkins remoting module using OpenTelemetry.
* Collected and reviewed 42 technical issues and 28 user voices on the remoting system to identify common issues by examining JIRA tickets from the past two years and conducting a user survey.

Skils:: Java / Maven / OpenTelemetry / Jenkins

Talks::
* https://www.cloudbees.com/videos/jenkins-remoting-monitoring-with-opentelemetry[DevOpsWorld 2021]
* https://cloudbees.techmatrix.jp/jenkins-day-japan2021[Jenkins Day Japan] (No public archive)

== Backend Engineer Internship @ Cookpad Inc.

Roll:: May 2019 - Nov 2020 : *Student internship*

* Improved the efficiency of operators and developers by developing tools for them.
* Reduced the time to build a Docker image from approximately 15 minutes to 7.5 minutes at best by optimizing the build process.

Skills:: Ruby on Rails / Docker / MySQL / Typescript / React

== Frontend Engineer Internship @ Arithmer Inc.

Roll:: Apr 2018 - Apr 2019 : *Part-time developer*

* Introduced React to the company and held a study session.

Skills:: Vanilla JS / Typescript / React
